### ISSUE TITLE
Restart timer

### ISSUE THREAD

**Issue by rdp2fm** [vydimitrov/react-countdown-circle-timer#1]
Is there a method to restart the timer? I am trying to restart the timer onComplete.

**Comment by vydimitrov** [comment]
Hey @rdp2fm, I would suggest passing a `key` prop to the `CountdownCircleTimer` component and changing it when the `onComplete` is invoked.

I was actually thinking to add a prop to repeat the counting animation once it is completed. Something like `isRepeated` which will restart the timer when it is completed. I was not sure what would be the use case for it but if there is one I can do it.

**Comment by rdp2fm** [comment]
I think there is a use case for this

**Comment by vydimitrov** [comment]
Sure, I will add it over the weekend.

**Comment by vydimitrov** [comment]
Hey @rdp2fm, I did change a bit the concept, so now you can return an array from `onComplete` with the following signature `[shouldRepeat: boolean, delay: number]`.  Read the docs for more info.
