### ISSUE TITLE
Add functionality to sync / count, based on system time.

### ISSUE THREAD

**Issue by HolimaX** [vydimitrov/react-countdown-circle-timer#11]
Is it possible to use timer with counting, based on system time, instead of time when site is loaded?

If so, could you share code snipp to achieve this, please?

**Comment by vydimitrov** [comment]
The timer is running based on a prop `isPlaying`, when the prop is set to `true` the timer runs. It is not based on the time site is loaded. It is using the JS internal time to measure the elapsed time.

https://github.com/vydimitrov/use-elapsed-time/blob/master/src/index.js#L11

**Comment by HolimaX** [comment]
> The timer is running based on a prop `isPlaying`, when the prop is set to `true` the timer runs. It is not based on the time site is loaded. It is using the JS internal time to measure the elapsed time.
> 
> https://github.com/vydimitrov/use-elapsed-time/blob/master/src/index.js#L11

Ok. Thanks. Understood. Then - how would I ensure that the time shown is identical / in-sync in any given time? I see that it is not consistent on page reload or rebuild events. Something like 'server-time' lock that would ensure that within, lets say, 24 hours frame the timer is running in predefined cycles...

**Comment by vydimitrov** [comment]
Lets say that you want the countdown to end on 2020-03-24T15:30:00Z (or 1585063800 in UNIX timestamp). So before rendering the countdown you get the current t time `new Date().getTime()` and subtract the current time from the end time, now you have the remaining time in seconds. You feed that time to the countdown component. On page reload you will do the same so the countdown will be always consistent.  Does this help?

**Comment by HolimaX** [comment]
> Lets say that you want the countdown to end on 2020-03-24T15:30:00Z (or 1585063800 in UNIX timestamp). So before rendering the countdown you get the current t time `new Date().getTime()` and subtract the current time from the end time, now you have the remaining time in seconds. You feed that time to the countdown component. On page reload you will do the same so the countdown will be always consistent. Does this help?

It does, but I have a bit different scenario - I need it to reoccur for infinity with x minute of countdown and y seconds of stop before new minute is started... so I cannot just assign time/date value to var and feed it in :(

**Comment by HolimaX** [comment]
> > Lets say that you want the countdown to end on 2020-03-24T15:30:00Z (or 1585063800 in UNIX timestamp). So before rendering the countdown you get the current t time `new Date().getTime()` and subtract the current time from the end time, now you have the remaining time in seconds. You feed that time to the countdown component. On page reload you will do the same so the countdown will be always consistent. Does this help?
> 
> It does, but I have a bit different scenario - I need it to reoccur for infinity with x minute of countdown and y seconds of stop before new minute is started... so I cannot just assign time/date value to var and feed it in :(

Can you please share your code/approach you would implement with your component?
