### ISSUE TITLE
Animation pausing when typing in textinput

### ISSUE THREAD

**Issue by mangicode** [vydimitrov/react-countdown-circle-timer#117]
Really enjoy the component, I was going to be using it in a trivia app, but unfortunately the animation stalls whenever the user is typing. This defect seems to render the component useless in my case, unless I am overlooking something. Thanks in advance for any clarification!

**Comment by vydimitrov** [comment]
Hey, can you share your code so I can try to spot the problem?

**Comment by vydimitrov** [comment]
Closing this one due to inactivity.
