### ISSUE TITLE
TypeError: s is not a function

### ISSUE THREAD

**Issue by saviomartin** [vydimitrov/react-countdown-circle-timer#123]
![scrnli_08_05_2021_18-39-48](https://user-images.githubusercontent.com/61895712/117540389-cda31a00-b02c-11eb-9ed2-9bd02aac3356.png)

I'm getting this error.

**Comment by vydimitrov** [comment]
How do you use the component? Can you share your code for the component?

**Comment by saviomartin** [comment]
I somehow was able to fix it up!

**Comment by talha131** [comment]
I faced the same issue. My mistake was making a string the child of `CountdownCircleTimer`. 


```jsx
<CountdownCircleTimer>
    hello
</CountdownCircleTimer>
```

It should be a function.

Like

```jsx
<CountdownCircleTimer>
    {({ remainingTime }) => remainingTime}
</CountdownCircleTimer>
```

_Hope it helps someone._
