### ISSUE TITLE
Version 2.5.2 broken on IE11

### ISSUE THREAD

**Issue by fmagaldea** [vydimitrov/react-countdown-circle-timer#130]
Version 5.2.1 works well, but the latest one crash on IE11 for some reason that I'm not sure because my IE11 test environment is hardly debuggable.

Anyway it would be nice for you to have at some point a test or something to check this kind of regression :)

**Comment by vydimitrov** [comment]
The bug is fixed in v2.5.3 by https://github.com/vydimitrov/react-countdown-circle-timer/commit/9eb01663e824b94779e3fdab60c31134e6448ca9. The IE support will be dropped in the next major release, which I am currently working on.
