### ISSUE TITLE
Change to Next Color without making a transition

### ISSUE THREAD

**Issue by BrnPer** [vydimitrov/react-countdown-circle-timer#133]
Hello everyone!

I think it would be awesome to have an option that would allow to change the color without making a transition between colors.
Sometimes the in between colors in a transition are not very readable. So I would like just to change the color without making a transition.

I hope that I could explain myself in a easy way. Sorry for my bad english 😅 
Thanks in advance!

**Comment by vydimitrov** [comment]
Hey @BrnPer, this is quite possible with the current API. Please refer to [this demo](https://codesandbox.io/s/ecstatic-driscoll-q1v75?file=/src/index.js)

**Comment by BrnPer** [comment]
Hi @vydimitrov yeah that was exactly what I was looking for 👍  But to me honest I don't understand why this is working 😕
Thanks in advance!

**Comment by vydimitrov** [comment]
May be reading [the props](https://github.com/vydimitrov/react-countdown-circle-timer#props-for-both-reactreact-native) for the `colors` prop may help you. But in essence:

```js
 ["#004777", 0.329] // it will take 0.329 of the total time to transition to the next color
 ["#004777", 0.001] // the next color is the same as the previous one so no transition. Also it will take 0.001 of the total duration to transition to the next color. Since the time is very short you do not get to see the transition so the next color starts right the way
 ["#F7B801", 0.329] // the same goes as the first one
```

**Comment by BrnPer** [comment]
Ohhhh I get it know! Thank you for your precious help! And awesome work in this package!
