### ISSUE TITLE
Gradient directions

### ISSUE THREAD

**Issue by iserzh** [vydimitrov/react-countdown-circle-timer#143]
Hi,

It will be great to make it possible to change gradient directions. Like we can pass custom x1, y1, x2, y2 coords as prop or custom linear gradient component at all. Why I need this? For example, with current implementation it's impossible to create gradients like this:
<img width="417" alt="Screen Shot 2021-05-31 at 15 07 21" src="https://user-images.githubusercontent.com/11062353/120190921-e8c70b00-c221-11eb-9aa7-cf5185f0fada.png">

Thanks!

**Comment by vydimitrov** [comment]
Hey @iserzh, thanks for the feature request - lets take the discussion [here](https://github.com/vydimitrov/react-countdown-circle-timer/discussions/67#discussioncomment-806668)
