### ISSUE TITLE
Using four circle timers for Days, Hours, Minutes, Seconds

### ISSUE THREAD

**Issue by UCAudio** [vydimitrov/react-countdown-circle-timer#15]
Hi, this isn't an issue (feel free to remove or I can delete), but I couldn't find any other contact info. Your circle timer is excellent and the best I've found for smooth/continuous timer display in React. 

I've been trying to come up with an implementation where I can use four of the timers to display a countdown from current date to an end date where the timers will displays remaining days, hours, minutes, and seconds. 

I have not yet been able to come up with an implementation that will work and was wondering if you have explored this at all yet or have any suggestions. Thanks.

**Comment by vydimitrov** [comment]
Hey @UCAudio, that sounds like an interesting one. Here is my first take on it - https://codesandbox.io/s/musing-davinci-mqssz?file=/src/App.js

It will require a bit of testing to make sure all works as expected. Let me know if you need anything else from me.

**Comment by vydimitrov** [comment]
I did add a section in the Readme on how to build the days, hours, minutes, seconds countdown - https://github.com/vydimitrov/react-countdown-circle-timer/tree/master/packages/web#days-hours-minutes-seconds-countdown

I will consider adding it as a new component to the library but that is a feature request.
