### ISSUE TITLE
MOBILE Countdown timer stalls onComplete until the screen is touched.

### ISSUE THREAD

**Issue by rpsutton** [vydimitrov/react-countdown-circle-timer#150]
I am developing with the most recent version of react-native on a real iPhone X that is running the most recent IOS. The timer component stalls on completion and does not update until the screen is pressed. However, I have written the exact same code in a [snack demo](https://snack.expo.io/@flexhedge/react-native-countdown-demo), and the snack demo functions as expected. I have attached a screen recording of my iPhone X running the same code. When the timer stalls and you then see the timer update, I have touched the screen with my finger. I cannot figure out why the same code works in the snack, but not on my device. Any thoughts? Thank you.

https://user-images.githubusercontent.com/57606697/122625933-a3099f80-d075-11eb-91bf-7b2da5c20d0d.MP4

**Comment by vydimitrov** [comment]
Hey, hmmm, that it is an interesting one, I am not sure what is the cause tho. One thing I can recommend by looking the code is this:

```js
 onComplete={() => {
    setKey((prevKey) => {
       const nextKey = prevKey + 1;
       previousTime.current = runSequence[nextKey];
       return nextKey;  
    });
  }}
```
This will guarantee that all usages of `key` are in sync, 

I guess you can try to reproduce it on a different real iPhone and see if the issue has anything to do with iPhone X.

**Comment by rpsutton** [comment]
Changing `onComplete` per your suggestion appears to work. Thank you! I am curious, though, how your version of the `onComplete` function guarantees that the key is in sync? Would you please explain what is happening in that code sinppet?

**Comment by vydimitrov** [comment]
This is how React works, you can read more about it [here](https://reactjs.org/docs/hooks-reference.html#functional-updates).

**Comment by rpsutton** [comment]
Hey @vydimitrov, the problem, unfortunately, reappeared after installing `react-native-haptic-feedback` and adding haptic feedback to the button.

**Comment by rpsutton** [comment]
Now I have deleted, rebuilt, and reinstalled the application onto my iPhone XR and the problem is solved once again, yet I changed no code. Any idea why this behavior is happening?

**Comment by vydimitrov** [comment]
It seems to me that some of your dependencies are causing the issue. One way to find out the cause would be to start a new project, add the timer and after that start adding your dependencies one by one. Then you can figure out which is the one that bugs it.
