### ISSUE TITLE
how to get state (isplaying or not) in between loop runs

### ISSUE THREAD

**Issue by oreon** [vydimitrov/react-countdown-circle-timer#156]
Building a react native workout app.
I am returning [true, 1500] as per the docs to have a 1.5 second rest interval in between workouts, when the timer is in this state I want to switch the workout image to a 'resting' image but can't do it since isplaying returns true . Maybe there is another property that I am not aware of.

**Comment by vydimitrov** [comment]
Hey, can you share your code with me and I will take a look on it? How do you change the image?

**Comment by oreon** [comment]
I got it to work thanks Vasil,
How do you change the transitions to vertical as in the third image on the
github page

Here is the code for anyone else who has a similar use case

export default function Workout() {
const sets = 2;
const exercises = 4;
const REST = 2;
const INTERVAL = 4;

const [isPlaying, setIsPlaying] = React.useState(false);

const [current, setCurrent] = React.useState(1);
const [setNumber, setSetNumber] = React.useState(1);
const [resting, setResting] = useState(false);
const [duration, setDuration] = useState(INTERVAL);

const finished = () => setNumber > sets;
const restart = () => {
setCurrent(1);
setSetNumber(1);
setResting(false);
};

//TODO : end workout , switch workout to upper body, play sound, r and l
leg, description

const avatarImage = () => {
switch (current) {
case 1:
return require("../assets/images/legs/squat.gif");
case 2:
return require("../assets/images/legs/lunge.gif");
case 3:
return require("../assets/images/legs/side-lunge.gif");
case 4:
return require("../assets/images/legs/glute_bridge.gif");

// case 3:
// return require("../assets/images/legs/lunge.gif");
// case 4:
// return require("../assets/images/legs/side-lunge.gif");
// case 5:
// return require("../assets/images/legs/side-lunge.gif");
// case 6:
// return require("../assets/images/legs/glute_bridge.gif");
}
};

let prev_resting = resting;

return (
<ScrollView
keyboardShouldPersistTaps="handled" // http://t.cn/EowE3r3
automaticallyAdjustContentInsets={false}
showsHorizontalScrollIndicator={false}
showsVerticalScrollIndicator={false}
>
<Card style={{ flex: 1, height: "100%" }}>
<Card.Title title="Lower body" />
<Card.Content>
{!finished() && (
<View>
<Title>
Set {setNumber} / {sets}
</Title>
<Text>
Exercise {current}/{exercises}
{/* {finished() ? "done" : "ongoing"} */}
</Text>

<CountdownCircleTimer
isPlaying={isPlaying}
key={duration}
duration={duration}
size={120}
colors={[
["#004777", 0.4],
["#F7B801", 0.4],
["#A30000", 0.2],
]}
onComplete={() => {
// console.log(resting.current);
prev_resting = resting;
setResting(!resting);
// console.log("is resting ->", prev_resting);
if (!prev_resting) {
setDuration(REST);

setCurrent(exercises !== current ? current + 1 : 1);
if (current == exercises) setSetNumber(setNumber + 1);
} else {
setDuration(INTERVAL);
}

// console.log("set->", setNumber);
// console.log("ex->", current);

return [!finished()];
}}
>
{({ remainingTime, animatedColor }) => (
<Animated.Text style={{ color: animatedColor, fontSize: 30 }}>
{remainingTime}
</Animated.Text>
)}
</CountdownCircleTimer>
{!resting && <Card.Cover source={avatarImage()} />}
{resting && <Title> Rest !</Title>}
<Button
title={isPlaying ? "Pause" : "Play"}
onPress={() => setIsPlaying((prev) => !prev)}
/>
</View>
)}
{finished() && (
<View>
<Button title={"Replay"} onPress={restart} />
<Title> Well done ! workout finsihed </Title>
</View>
)}
</Card.Content>
</Card>
</ScrollView>
);
}

**Comment by vydimitrov** [comment]
[Here is the React demo](https://codesandbox.io/s/silly-night-d3s70?fontsize=14&hidenavigation=1&theme=dark) - hope it will help you to figure out how to implement the same with ReactNative.
