### ISSUE TITLE
Changelog not reflecting changes since v2.0.0

### ISSUE THREAD

**Issue by fmagaldea** [vydimitrov/react-countdown-circle-timer#17]
At least since version 2.0 there are 5 new versions, but only few of them are described in `CHANGELOG.md` for web, `README.md` nor Github `https://github.com/vydimitrov/react-countdown-circle-timer/releases`.

Please add in one of these 2 places (or an external website) the diff for each version, thanks !

**Comment by vydimitrov** [comment]
Hey, sure, my bad, got stuck doing a lot of small changes here and there. I will update the Change log file and let you know. I guarantee you that all changes are small cosmetic things here and there.

**Comment by vydimitrov** [comment]
Hey @fmagaldea, here you go - https://github.com/vydimitrov/react-countdown-circle-timer/blob/master/packages/web/CHANGELOG.md

**Comment by fmagaldea** [comment]
Perfect, thanks!
