### ISSUE TITLE
Start/Restart timer on button click

### ISSUE THREAD

**Issue by DICOT4** [vydimitrov/react-countdown-circle-timer#173]
Is there a way to start/restart the timer on the button click?

For example:
```node
const [isPlaying, setIsPlaying] = useState(true);
const [timer, setTimer] = useState(10);

<CountdownCircleTimer
  key={'thisIsMyUniqueKey'}
  isPlaying={isPlaying}
  duration={timer}
  size={150}
  strokeWidth={5}
  colors={[
      ['#FF7300', 1],
      ['#218380']
  ]}
  onComplete={() => {
      setIsPlaying(false);
      setTimer(0);
      return [false];
  }}
>

<button type="button" className="btn btn-primary px-3" onClick={() => {
  setTimer(10);
  setIsPlaying(true);
}}>
  Reset
</button>
```

I'm trying like the above example but it doesn't seem to work. I noticed that as soon as the button sets the `isPlaying` to `true`, the `onComplete` function gets called instantly.

**Comment by vydimitrov** [comment]
Hey, check the recipes and you will find your answer - https://github.com/vydimitrov/react-countdown-circle-timer#recipes

**Comment by DICOT4** [comment]
Thank you for the prompt response. It seems to be working with the change of the `key` prop. However, I feel there can be a better control for that (e.g. a method to pause or restart).
