### ISSUE TITLE
Center offset

### ISSUE THREAD

**Issue by 1280103995** [vydimitrov/react-countdown-circle-timer#175]
This bug appears on both Android and iOS.
<img width="377" alt="2021-09-2910 11 54" src="https://user-images.githubusercontent.com/17424486/135191371-8aca42f7-0038-49c9-aa5e-98156e86ff00.png">

```
export default class App extends React.PureComponent {

  render() {
    return (
      <CountdownCircleTimer
        size={280}
        strokeWidth={14}
        strokeLinecap={'square'}
        colors={'red'}
        duration={100}
        initialRemainingTime={100}
      >
        <View style={{flex:1, justifyContent:'center',alignItems:'center'}}>
          <View style={{width: 1, height: '100%',backgroundColor: 'blue'}}/>
          <View style={{position: 'absolute', width: '100%', height: 1,backgroundColor: 'green'}}/>
        </View>
      </CountdownCircleTimer>
    );
  }
}
```

```
"react": "17.0.1",
"react-native": "0.64.2",
"react-native-countdown-circle-timer": "^2.5.4"
```

**Comment by vydimitrov** [comment]
It seems quite centered to me. I am not sure what is your setup. Please create a demo where you reproducing the issue and I can take a look on it.

Check the Snack below:
https://snack.expo.dev/bttGD8k4N?platform=ios

![image](https://user-images.githubusercontent.com/10707142/135303430-507f91b9-681f-4251-9949-cc426e6fe704.png)

**Comment by 1280103995** [comment]
I ran your code locally on the computer and reproduced the problem. But it is normal on the browser. So I think this is a bug in the native code.

Android: Samsung A51 (Android 11)
iOS: iPhone XR (ios 15)

<img src="https://user-images.githubusercontent.com/17424486/135378898-526d2f67-a6f7-496e-bcdf-61070e287890.png" width="60%" height="60%"/>

**Comment by vydimitrov** [comment]
This is my phone - iPhone 11 ios15
![IMG-1001](https://user-images.githubusercontent.com/10707142/135583612-14a9e494-2e6e-436d-9794-b32e493ced0a.PNG)

Please test it outside your App.

**Comment by 1280103995** [comment]
This is not a bug, it is a problem with my application.
