### ISSUE TITLE
Change the view of user interface

### ISSUE THREAD

**Issue by berkaygurbuz** [vydimitrov/react-countdown-circle-timer#178]
I want to change the circle user interface. Is there any way to change circle as follows image:
![1](https://user-images.githubusercontent.com/61121747/139056070-f5725ff6-54c0-42f6-b104-0daaf3b677d5.PNG)

**Comment by berkaygurbuz** [comment]
@vydimitrov You can follow the idea in this [forked repository](https://github.com/berkaygurbuz/react-countdown-circle-timer)

**Comment by vydimitrov** [comment]
Great, it looks good so far. Let me know if you want me to look at some part of it and help you.

**Comment by berkaygurbuz** [comment]
@vydimitrov I can't figure out the getPathProps method. I create svg but it doesn't rotate. I think we have to change it to our custom svg. Maybe you can help me in this method.

**Comment by vydimitrov** [comment]
I tried a few different things but I was not really able to get it 100% as on the design. I would recommend you to dig in a bit more in to `ClipPath` function. Unfortunately, the `strokeDasharray` on the clip path is not taken and it is not applied on the animated path. Check the snippet below:

```js
<ClipPath id="myClip">
  <Path
    fill="none"
    d={path}
    strokeWidth="20"
    strokeDasharray="2"  // This will not apply on the animated path when used as a clip path
  />
</ClipPath>
<AnimatedPath
  stroke="#000"
  d={path}
  strokeDasharray={pathLength}
  strokeDashoffset={strokeDashoffset}
  strokeWidth={strokeWidth}
  clipPath="url(#myClip)"
/>
```
I'd suggest to try to find a different way how you can clip the animated path. One idea is to use an image from your design instead, like so (sudo code below):
```js
<ClipPath id="myClip">
  <Image src="./image/from/design.png" />
</ClipPath>
<AnimatedPath
    stroke="#000"
    d={path}
    strokeDasharray={pathLength}
    strokeDashoffset={strokeDashoffset}
    strokeWidth={strokeWidth}
    clipPath="url(#myClip)"
/>
```

**Comment by vydimitrov** [comment]
This is my best attempt IMO. Make the animated path transparent and put behind your path with the `strokeDasharray="2"` 

<img width="400" src="https://user-images.githubusercontent.com/10707142/140624063-4fb1dafa-8668-4b9c-925d-6ae7049719e5.PNG" />

**Comment by berkaygurbuz** [comment]
Can you animate the circle? It looks not bad I think.

**Comment by vydimitrov** [comment]
Yes, you need to just this one
```js
{isProgressPathVisible && (
  <>
    <Path
      fill="none"
      stroke="#ccc"
      d={path}
      strokeWidth="20"
      strokeDasharray="2"
    />
    <AnimatedPath
      fill="none"
      stroke="rgba(0,0,0,0.3)"
      d={path}
      strokeWidth="20"
      strokeDasharray={pathLength}
      strokeDashoffset={strokeDashoffset}
    />
  </>
)}
```

**Comment by berkaygurbuz** [comment]
Maybe we have to know how to add some margin between circle stick.

**Comment by vydimitrov** [comment]
Try this `strokeDasharray="2 4"`

**Comment by berkaygurbuz** [comment]
I change ```strokeDashArray="3 8"```. I got similar design but the working logic is a little different. Circle starts blank screen because I choose ```stroke="white"``` in animatedPath and when time is increasing, design is rotating.

```
        <Path
          fill="none"
          strokeWidth={trailStrokeWidth ?? strokeWidth}
          stroke={trailColor}
          d={path}
        />
        {isProgressPathVisible && (
          <>
          <Path
      fill="none"
      stroke="black"
      d={path}
      strokeWidth="20"
      strokeDasharray="3 8"
    />
          <AnimatedPath
             fill="none"
             stroke="white"
             d={path}
             strokeWidth="22"
             strokeDasharray={pathLength}
             strokeDashoffset={strokeDashoffset}
          />
          </>
```
```trailColor``` is also white. You can change colors depends on your background color.

![image](https://user-images.githubusercontent.com/61121747/141452783-f4da0ca3-6a7f-4111-993b-6addaa719795.png)


Maybe you can help smooth rotation effects and develop working logic same as my first design.

**Comment by vydimitrov** [comment]
May be you can try to add one new `Path` after the `AnimatedPath` so it will be always shown since it will be on top of it. If the new `Path` has some opacity on it, you can make it looks close to the design but inverted - the remaining time will have lighter color and the elapsed time will have darker color. Is that going to work for you?

**Comment by berkaygurbuz** [comment]
I think this [solution](https://github.com/vydimitrov/react-countdown-circle-timer/issues/178#issuecomment-966995158) is enough for me. Thanks for the help.
