### ISSUE TITLE
need use multiple countdown

### ISSUE THREAD

**Issue by amirsamani** [vydimitrov/react-countdown-circle-timer#182]
hi,
i use a countdown in each row of a table
I want to delete that row when the each count down timer complete
please help me.

**Comment by vydimitrov** [comment]
Hey, you can hook to the [`onComplete` method](https://github.com/vydimitrov/react-countdown-circle-timer#props-for-both-reactreact-native) and add your logic to delete the row

**Comment by amirsamani** [comment]
thanks is there any way to access parent tr of completed countdowntimer in onComplete method?

**Comment by vydimitrov** [comment]
This depends of your implantation. Usually you pass a prop, which is a method/function from the parent to the children. Then in the `onComplete` you call the prop/method and the parent takes it from there.

**Comment by vydimitrov** [comment]
Let me know if you need any additional help on this one.
