### ISSUE TITLE
Display oncomplete Remaining time

### ISSUE THREAD

**Issue by kingshax** [vydimitrov/react-countdown-circle-timer#184]
Hello, is there any way to display the time remaining left before the timer restart ?
example: once my 10 seconds are gone, I want to show the remaining time before the timer reset.

Thank you

**Comment by vydimitrov** [comment]
Hey, the [`children` prop](https://github.com/vydimitrov/react-countdown-circle-timer#props-for-both-reactreact-native) receives also the remaining time.

**Comment by kingshax** [comment]
Hey,

I mean I already managed to start the timer and display it with the remainingTime, it already restart at a certain time based on user input.
I'm having trouble displaying the reset time plus it does not decrement itself (atleast when I'm displaying it) otherwise the reset functionnality works well with the onComplete..

Dunno if I'm clear ><

**Comment by vydimitrov** [comment]
You will need to pass a `key` prop to the component and change the value when you want to reset the animation while the timer is running. You can check the receipts there are some examples on how to do it.

**Comment by vydimitrov** [comment]
Here is a demo https://codesandbox.io/s/tender-bogdan-qd35m

**Comment by kingshax** [comment]
I think it will be better with this: 
https://user-images.githubusercontent.com/35834812/143027083-f9d88e9e-5e20-4333-bb73-3aa8ea4808a5.mov


I just want instead of the 'finished!', to display the 2 seconds that are being returned, the ones in the 'rest time'. 
Really can't figure it out, maybe it doesn't fit with the countdownTimer..?

**Comment by vydimitrov** [comment]
I am not able to see the video. Can you try to add it here in the bug or create a  codesandbox so I can see?

**Comment by vydimitrov** [comment]
I am closing this bug, let me know if you need any additional help.
