### ISSUE TITLE
Different duration on Repeat

### ISSUE THREAD

**Issue by kushal-g** [vydimitrov/react-countdown-circle-timer#19]
Is there a way we can have different durations for the timer when it is repeated upon completion?

**Comment by vydimitrov** [comment]
Hey, there is no API for this, but you can easily do it. Please refer to the codesandbox below:

https://codesandbox.io/s/amazing-montalcini-zy85d?file=/src/index.js

Let know if it works for you.

**Comment by kushal-g** [comment]
Yup that worked for me. Thanks!
