### ISSUE TITLE
Feature request: more precision

### ISSUE THREAD

**Issue by Hirbod** [vydimitrov/react-countdown-circle-timer#191]
Hi, lovely lib and nice rewrite. The `onUpdate` callback is also nice, but I need a bit more precision.
I am using the timer to show time left to record a video. The video record can be done in segments and the timer will recreate itself always based on remaining time etc.

I am working with ffprobe to get the exact duration of my recorded videos and the user is not allowed to exceed the max duration, and it is important that onComplete does trigger with the exact duration. But you're rounding with `Math.ceil`, which breaks it for me, as every "stop" on my recording sessions will round my numbers, return a wrong onUpdate remainingTime value etc.

Could you add a prop like `preciseTimes` and just accept that I am going to pass stuff like 9.487000 and also return the same precision back in all callbacks? I really don't want to fork this project because something small like this :D

Thanks in advance.

**Comment by Hirbod** [comment]
Hi @vydimitrov, thanks for rubberducking with me. I got a solution now :D

**Comment by vydimitrov** [comment]
Yup, you can use the `elapsedTime` to display the remaining time, which has the full precision you need. Check it here:

https://codesandbox.io/s/flamboyant-cartwright-1vz3q?file=/src/index.js

Is this what you need?

**Comment by Hirbod** [comment]
My issue was, that onComplete triggered `setRemainingRecordingTime(0)`, but once `recordedClips` effect triggered (and ffprobe runs async`,  I will have a different total duration (because ffprobe is counting based on video frames).

And my reduce function will most likely be off. I just added a check that once onComplete triggered the value(0), that I am not updating the remainingTime again.
