### ISSUE TITLE
use pnpm/npm/yarn can build , can't found @countdown/shared

### ISSUE THREAD

**Issue by awkj** [vydimitrov/react-countdown-circle-timer#193]
![image](https://user-images.githubusercontent.com/9017743/152685191-30198fe6-130b-4887-96af-109e6da6c110.png)

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/9017743/152685255-d2029ac9-3044-4e52-9ee9-9393fccf7f2c.png">

I use vite to preview and run my app, I found if vite dev , than it will work ,but vite build has this error, and vscode can't find the dependecies, when I delete it ,the lib work prefect, I guess you forget delete it ?

<img width="969" alt="image" src="https://user-images.githubusercontent.com/9017743/152685332-d138b2b9-7959-4b09-9b62-d376b6fd44b5.png">

**Comment by vydimitrov** [comment]
Hey @awkj, thanks for reporting this issue. I am not sure what are you trying to do. Are you trying to use the hook? I guess this is only type error, because the hook code is bundled together with component, and does not have any external dependencies.

**Comment by vydimitrov** [comment]
It it works fine in Codesanbox - https://codesandbox.io/s/stupefied-cray-z2o4t?file=/src/App.tsx, I just need to understand how you use it. I know what there is a problem with the types, since I was not able to find a way to bundle them as well. When TS sees the third part import (my own shared package) then it just references them but does not add them to the output declarations.

**Comment by awkj** [comment]
I think your build package is have type problem( I'm react beginner, so sorry I can't give your fix help),

If you want retry this problem, you can jump to the file 'countdownCircleTimer.d.ts‘ and will see the tips.
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/9017743/152748508-b18ee678-e9b7-4718-9f2a-b5f75470a196.png">

**Comment by vydimitrov** [comment]
Yup, I am aware of the type problem... it is just that I am not able to bundle the types when bundling the code. But nevertheless the code works as expected. I will keep the bug open and try to find a way to add the types to the package.

**Comment by vydimitrov** [comment]
Hey @awkj, this issue is now fixed in 3.0.9 Please check it let me know if it works as expected.
