### ISSUE TITLE
How to make incremental count 

### ISSUE THREAD

**Issue by rajeevverma076** [vydimitrov/react-countdown-circle-timer#197]
I wanted to know I can clock incremental way. There are no props available for this. Can someone help me with this?

**Comment by vydimitrov** [comment]
Hey @rajeevverma076, can you give a bit more info on what you want to achieve?

**Comment by rajeevverma076** [comment]
Hi @vydimitrov 

I wanted to achieve incremental count down. For example, if I will click on any button my timer will start in an incremental way, not decremental. Currently it is working count down in incremental only. 

Ex- https://codepen.io/ninjascribble/pen/DRPwQY

**Comment by vydimitrov** [comment]
Do you need the circle animation or just the count up numbers?

**Comment by vydimitrov** [comment]
How about this one? https://codesandbox.io/s/cool-bardeen-0e3gu1?file=/src/index.jss

**Comment by rajeevverma076** [comment]
> 

circle animation same as  [react-countdown-circle-timer]

**Comment by rajeevverma076** [comment]
> How about this one? https://codesandbox.io/s/cool-bardeen-0e3gu1?file=/src/index.jss

This is good but   duration={10} should be dymanic. Means no limit.

**Comment by rajeevverma076** [comment]
How to used children props.

const children = ({ remainingTime }) => {
  const minutes = Math.floor(remainingTime / 60)
  const seconds = remainingTime % 60
  return `${minutes}:${seconds}`
}

**Comment by rajeevverma076** [comment]
Please help me with this.
const children = ({ remainingTime }) => {
const minutes = Math.floor(remainingTime / 60)
const seconds = remainingTime % 60
return ${minutes}:${seconds}
}

**Comment by vydimitrov** [comment]
> This is good but duration={10} should be dymanic. Means no limit.

Just past big enough number

**Comment by vydimitrov** [comment]
> Please help me with this.
> const children = ({ remainingTime }) => {
> const minutes = Math.floor(remainingTime / 60)
> const seconds = remainingTime % 60
> return ${minutes}:${seconds}
> }

What do you want me to help you with?

**Comment by rajeevverma076** [comment]
Hello @vydimitrov 

Thank you for your prompt response to my query. Can you please let me know one more query it is possible to show the progress bar on the continuous way with stoping watch and I will pass props once the process has been completed?
For example, I have pass duration={100}  and my process completed in 60 seconds till the time progress bar should continually run like this. https://codesandbox.io/s/ccttsj?file=/demo.js

**Comment by vydimitrov** [comment]
Let me know if you manage to achieve what you wanted so I can close the issue.

**Comment by vydimitrov** [comment]
Closing this issue, let me know if you have any other questions.
