### ISSUE TITLE
Cannot read property 'duration' of undefined

### ISSUE THREAD

**Issue by reggieofarrell** [vydimitrov/react-countdown-circle-timer#20]
I'm trying to implement this timer component in a realtime web application with Firebase.  The timer is getting it's props from Firebase and is being controlled via an admin interface where the values are being updated.  It is somewhat randomly crashing when the timer completes though and displaying both of these errors...

```
Uncaught TypeError: Cannot read property 'duration' of undefined
    at index.js:1
    at CountdownCircleTimer (index.js:1)
```
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```
I can pretty consistently make it crash on completion by changing the duration while it's running to a shorter time than what was originally set.  

Conversely, if I set it to longer that the initial duration while it's running, the countdown won't complete.  It will get stuck at the difference of the original duration and the new duration.  Such as, if it was originally 10 seconds and then I pass it a new duration on the fly of 12, it will get stuck when it reaches 2 seconds.  

Is dynamically setting the duration while the timer is running not supported?

Here is my code on the user side (we call them 'participants')...
```javascript
import React, { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import { useFirestore } from 'react-redux-firebase'
import moment from 'moment';
import "moment-duration-format";

import { CountdownCircleTimer } from 'react-countdown-circle-timer';

import './participantTimer.scss';

const ParticipantTimer = ({session}) => {
  // session object comes from Firebase and can be
  // updated on the fly while the timer is running which
  // would push a new duration into the timer component
  const [durationSeconds, setDurationSeconds] = useState(0);
  const timerValue = session.timerValue || 0;
  const timerRunning = session.timerRunning || false;
  const timerStartedAt = session.timerStartedAt || 0;
  const db = useFirestore();

  useEffect(() => {
    // if the participant joined after the timer was started by the admin,
    // make sure they are seeing the same time as everyone else
    let duration = timerRunning && timerValue
      ? timerValue - (db.Timestamp.now().seconds - timerStartedAt)
      : timerValue;

    if (duration < 0) {
      // this could happen if the user refreshes the
      // page while the timer is running
      duration = 0;      
    }

    setDurationSeconds(duration);
  }, [timerValue, timerStartedAt, timerRunning])

  const renderTime = value => {
    const renderedTimer = value > 60
      ? moment.duration(value, 'seconds').format('m:ss')
      : value;

    return (
      <div className="timer">
        <div className="value">{renderedTimer}</div>
      </div>
    );
  };

  return (
    <div className="participant-timer">
      <CountdownCircleTimer
        key={timerStartedAt}
        isPlaying={timerRunning}
        durationSeconds={durationSeconds}
        colors={[['#d9d9d9', 0.0001],["#02A05C", 0.89], ["#02A05C", 0.01], ["#E2351E"]]}
        renderTime={renderTime}
        onComplete={() => [false, 0]}
        size={160}
        strokeWidth={15}
      />
    </div>
  )
}

ParticipantTimer.propTypes = {
  session: PropTypes.object.isRequired
}

export default ParticipantTimer
```
...and here is the code on the admin side where the timer values are being updated.  This view also display's the timer for the admin. Ideally the admin and participants all see basically the same thing...
```javascript
import React, { useState, useEffect } from 'react'
import PropTypes from 'prop-types'
import { useFirestore } from 'react-redux-firebase'
import moment from 'moment';
import "moment-duration-format";

import { CountdownCircleTimer } from 'react-countdown-circle-timer';
import Button from '@material-ui/core/Button';
import Typography from '@material-ui/core/Typography';
import TextField from '@material-ui/core/TextField';

import ActionDialog from '../Dialogs/ActionDialog';

const AdminTimer = ({session}) => {
  // session is also coming from firebase here
  const [showDialog, setShowDialog] = useState(false);
  const [minutes, setMinutes] = useState(0);
  const [seconds, setSeconds] = useState(0);
  const [durationSeconds, setDurationSeconds] = useState(0);
  const timerValue = session.timerValue || 0;
  const timerRunning = session.timerRunning || false;
  const timerStartedAt = session.timerStartedAt || 0;
  const db = useFirestore();

  useEffect(() => {
    let duration = timerRunning && timerValue
      ? timerValue - (db.Timestamp.now().seconds - timerStartedAt)
      : timerValue;

    if (duration < 0) {
      duration = 0;      
    }

    setDurationSeconds(duration);
  }, [timerValue, timerStartedAt, timerRunning])

  const setSessionTimer = async (timerMinutes = 0, timerSeconds = 0) => {
    const actualSeconds = +timerMinutes * 60 + +timerSeconds;

    await db.doc(`sessions/${session.id}`).update({ 
      timerValue: actualSeconds,
      timerRunning,
      timerStartedAt: timerRunning ? db.Timestamp.now().seconds : timerStartedAt,
    });

    setShowDialog(false);
  }

  const startSessionTimer = async () => {
    const fbTime = db.Timestamp.now().seconds;

    await db.doc(`sessions/${session.id}`).update({ 
      timerRunning: true,
      timerStartedAt: fbTime
    });
  }

  const cancelSessionTimer = async () => {
    await db.doc(`sessions/${session.id}`).update({ 
      timerRunning: false,
      timerValue: 0,
      timerStartedAt: 0,
    });
  }

  const timerEnded = () => {
    setTimeout(() => {
      db.doc(`sessions/${session.id}`).update({ 
        timerValue: 0,
        timerStartedAt: 0,
        timerRunning: false,
      })
    }, 1000);
  }

  const onComplete = () => {
    timerEnded();

    return [false, 0];
  }

  const renderTime = value => {
    const renderedTimer = value > 60
      ? moment.duration(value, 'seconds').format('m:ss')
      : value;
  
    return (
      <div className="timer">
        <div style={{fontSize: '20px'}}>{renderedTimer}</div>
      </div>
    );
  };

  return (
    <div className="d-flex flex-column">
      <Button onClick={() => setShowDialog(true)}>
        <CountdownCircleTimer
          key={timerStartedAt}
          isPlaying={timerRunning}
          durationSeconds={durationSeconds}
          colors={[['#d9d9d9', 0.0001],["#02A05C", 0.89], ["#02A05C", 0.01], ["#E2351E"]]}
          renderTime={renderTime}
          onComplete={onComplete}
          size={80}
          strokeWidth={5}
        />
      </Button>
      {(!timerRunning) &&
        <Button onClick={startSessionTimer} className="align-self-center">
          Start
        </Button>
      }
      {timerRunning &&
        <Button onClick={cancelSessionTimer} className="align-self-center">
          Cancel
        </Button>
      }
      {/* Form Dialog for setting the timer */}
      <ActionDialog
        onClose={() => setShowDialog(false)}
        open={showDialog}
        contentClassNames="d-flex justify-content-center"
        actionsClassNames="d-flex justify-content-between"
        title="Set Session Timer"
        maxWidth="xs"
        actions={[
          { label: 'Cancel', onClick: () => setShowDialog(false) },
          { label: 'Set Timer', onClick: () => setSessionTimer(minutes, seconds) }
        ]}>
        <div className="d-flex align-items-end">
        <TextField
            name="name"
            type="number"
            label="Minutes"
            value={minutes}
            onChange={event => setMinutes(event.target.value)}
            InputProps={{
              style: { maxWidth: 44 }
            }}
            inputProps={{
              min: '0'
            }}
          />
          <Typography className="mx-3">:</Typography>
          <TextField
            name="seconds"
            type="number"
            label="Seconds"
            inputProps={{ max: '60', min: '0' }}
            value={seconds}
            onChange={event => setSeconds(event.target.value)}
            InputProps={{
              style: { maxWidth: 44 }
            }}
          />
        </div>
      </ActionDialog>
    </div>
  )
}

AdminTimer.propTypes = {
  session: PropTypes.object.isRequired
}

export default AdminTimer
```

Any idea what is happening here?  We need to be able to update the duration dynamically on the fly while the timer is running.

**Comment by vydimitrov** [comment]
Hey @reggieofarrell, thanks for reporting this issue. I will need to investigate the duration bug. This is the first time someone asking for changing the duration dynamically. Here are few things that come to my mind before fully investigating it:

- the timer won't be restarted when changing the duration, you will need to take care of that by changing the `key` prop of the `CountdownCircleTimer` when the duration changes, like so:

```jsx
<CountdownCircleTimer
          key={timerStartedAt + duration}
          isPlaying={timerRunning}
          durationSeconds={durationSeconds}
          colors={[['#d9d9d9', 0.0001],["#02A05C", 0.89], ["#02A05C", 0.01], ["#E2351E"]]}
          renderTime={renderTime}
          onComplete={onComplete}
          size={80}
          strokeWidth={5}
        />
```
Check this codesandbox - https://codesandbox.io/s/admiring-nightingale-7bt9o?file=/src/index.js

- I've seen the warning when repeating the timer and the same time the component is unmounted. This should be fixed in the latest version `v2.1.1`. Please upgrade `react-countdown-circle-timer` to the latest version so we are on the same page. Just keep in mind that there are some minor API change , read more about it here - https://github.com/vydimitrov/react-countdown-circle-timer/blob/master/packages/web/MIGRATE_TO_V2.md

- Side node, you don't need to return an array from `onComplete` handler if you don't want the timer to repeat. This will clear the code a bit. 

Changing the `key` prop of `CountdownCircleTimer` component when the duration changes should solve your problem. I will investigate the original issue. Thanks for reporting.

**Comment by reggieofarrell** [comment]
Thanks for the quick response @vydimitrov.  Looks like updating to the latest version and implementing `key={timerStartedAt + duration}` has fixed the issue where the timer wasn't completing if it was set to a higher duration than initial while it is running.  It's also not consistently crashing (or at all so far) when setting the duration to a lower value than initial while it is running.  Will have to do some more testing, but this has helped immensely.  What's strange is that the key prop was already changing because I was always updating `timerStartedAt` at the same time as duration, but for some reason `timerStartedAt + duration` is working better 🤷🏻‍♂️.  I see you made a new commit as well.  I'll keep a look out for a new version.

**Comment by vydimitrov** [comment]
As long as you pass a new value to the `key` prop when the duration changes, the component will start over regardless of the duration value (higher or lower than the previous one). This is how React works, passing a new value to the `key` prop causes the component to be reinitialized, which in this case means that the timer will start over. Just make sure that you pass a new value every time the duration changes, one way to do it is to increment a counter.

I am implementing some guards again changing the duration while the timer is running. The main reason is that the timer relays on the elapsed time since it is running and changing the duration causes a lot of inconsistencies with the remaining time, color and bar progress. Still the recommended way to change the duration once the component is mounted is to pass a new `key` to the component.

**Comment by vydimitrov** [comment]
Let me know if you need anything else from me. I did close the issue with my comment above.
