### ISSUE TITLE
Compilation error : TS2693: 'string' only refers to a type, but is being used as a value here.

### ISSUE THREAD

**Issue by PadBol76** [vydimitrov/react-countdown-circle-timer#206]
Hello,

Thanks a lot for this module !

We use this module in our project and TS compilation found 4 errors.
You will find the lines concerned below :

https://github.com/vydimitrov/react-countdown-circle-timer/blob/ecfb606f848a83a0a38e9f48ce3232db83e83023/packages/shared/src/types.ts#L3
https://github.com/vydimitrov/react-countdown-circle-timer/blob/ecfb606f848a83a0a38e9f48ce3232db83e83023/packages/shared/src/types.ts#L4
https://github.com/vydimitrov/react-countdown-circle-timer/blob/ecfb606f848a83a0a38e9f48ce3232db83e83023/packages/shared/src/types.ts#L5
https://github.com/vydimitrov/react-countdown-circle-timer/blob/ecfb606f848a83a0a38e9f48ce3232db83e83023/packages/shared/src/types.ts#L6

To resolve the problem in our project we added this in tsconfig.json :
```
"compilerOptions": {
    ...
    "skipLibCheck": true
}
```

Best regards.

**Comment by vydimitrov** [comment]
Hey @PadBol76, what version of TS do you run?

**Comment by PadBol76** [comment]
We run it with TS 3.7.3

**Comment by vydimitrov** [comment]
I see, the [template literal type](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html) were introduced in v4 so if you upgrade your TS you wont get the error anyl onger.
