### ISSUE TITLE
Typescript error: type expected

### ISSUE THREAD

**Issue by alessandro-caiora** [vydimitrov/react-countdown-circle-timer#209]
Hi @vydimitrov, 
I get this error when trying to start my react app. I simply used the code written in documentation. How can I solve the issue?
![Schermata 2022-05-25 alle 16 57 33](https://user-images.githubusercontent.com/8128456/170295768-22605476-dc3b-4f03-b7f7-26123663364d.png)

Regards,
Alessandro

**Comment by vydimitrov** [comment]
What is the TypeScript version you are using?

**Comment by alessandro-caiora** [comment]
3.9.6

**Comment by vydimitrov** [comment]
Check [this](https://github.com/vydimitrov/react-countdown-circle-timer/issues/206#issuecomment-1107415688) one
