### ISSUE TITLE
CountdownCircleTimer background color ? 

### ISSUE THREAD

**Issue by bl1lnk** [vydimitrov/react-countdown-circle-timer#211]
is there away to change CountdownCircleTimer background color ?

**Comment by vydimitrov** [comment]
Hey @bl1lnk, the background color should be transparent so you can just change it yourself.

**Comment by bl1lnk** [comment]
lol its that simple . thanks

**Comment by zhifeng-heng** [comment]
Hi @bl1lnk , i'm trying to change the inside circle's background color. Is this what you were asking back then, or if you happen to know how to do it?

Thanks!

**Comment by vydimitrov** [comment]
Hey @zhifeng-heng, is this going to work for you - https://codesandbox.io/s/gracious-elbakyan-uzlg1y?file=/src/styles.css

wrap timer in an element and add these styles (based on your timer size - this case 180px)
```
  width: 180px;
  height: 180px;
  border-radius: 99999px;
```

**Comment by zhifeng-heng** [comment]
Thank you @vydimitrov , this is exactly what i need! :)
