### ISSUE TITLE
React Native compatibility?

### ISSUE THREAD

**Issue by MarcoFromBerlin** [vydimitrov/react-countdown-circle-timer#22]
Hi!
It looks cool, I'm trying to use it on RN but doesn't seem to work.
It always gives me `Invariat violation`.
Any advice?

**Comment by vydimitrov** [comment]
Hey, did you install the react-native package? Can you share some code snippet so I can take a look on it?

**Comment by vydimitrov** [comment]
It seems fine here - https://snack.expo.io/@vydimitrov/countdown-circle-timer?session_id=snack-session-8tgDhia5f&preview=true&platform=ios&iframeId=4a80oah677&theme=light

**Comment by MarcoFromBerlin** [comment]
thanks!
Actually I didn't. I uninstall the old one and I installed the native version but I get this

`error: Error: Unable to resolve module `react-native-svg` from `node_modules/react-native-countdown-circle-timer/lib/index.js`: react-native-svg could not be found within the project.
`
I tried a bit of everything to fix it but didn't succeed.
Any idea?
Thannks

**Comment by vydimitrov** [comment]
Yup, the package has a dependency on react-native-svg, please add it to your app

**Comment by MarcoFromBerlin** [comment]
Thanks a lot!
Sorry for the silly questions but I'm new here

**Comment by MarcoFromBerlin** [comment]
Everything works, but I'm tring to give the `duration` through a state (in seconds) but I get :

Invalid Violation: Inputrange must be monotonically non-decreasing 0, NaN,NaN,NaN

Sounds strange cause I set the `isPLaying` with a state and works

**Comment by vydimitrov** [comment]
Currently, there is no support for `useNativeDriver` but it is on the roadmap.

**Comment by vydimitrov** [comment]
If you want me to help you, you should share some code with me, otherwise I am just guessing what is the problem.

**Comment by MarcoFromBerlin** [comment]
Thanks!
I just would like to know if there's a way to silent that warn, but it's not so important

**Comment by vydimitrov** [comment]
Hey @MarcoFromBerlin, just wanted to let you know that the error below is now fixed in v.2.1.1

Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to true or false
