### ISSUE TITLE
updateInterval not working for 1 second

### ISSUE THREAD

**Issue by avijit-ordering** [vydimitrov/react-countdown-circle-timer#226]
Hello,

By default updateInterval works for 2 seconds.
If we set updateInterval:1 then it's not working but if we set updateInterval:5 then it's working. I want the interval for 1 sec instead of 2 seconds.

I have used     "react-native-countdown-circle-timer": "^3.1.0",
Can you please look into this?

Thanks.

**Comment by avijit-ordering** [comment]
This is my code: 
             <CountdownCircleTimer
                  isPlaying
                  duration={10}
                  colors={['#004777', '#F7B801', '#A30000', '#A30000']}
                  colorsTime={[300, 200, 100, 0]}
                  onComplete={onComplete} 
                  updateInterval={1}>
                  {({ remainingTime }) => <OText>{remainingTime}</OText>}
                </CountdownCircleTimer>

**Comment by vydimitrov** [comment]
Hey, sure I can look at it. Can you prepare a small demo reproducing the issue?

**Comment by avijit-ordering** [comment]
@vydimitrov Please check this video screen https://d.pr/v/1jijii

**Comment by vydimitrov** [comment]
@avijit-ordering it seems to be working fine, you can take a look on it here - https://snack.expo.dev/@dimitrov/countdown-circle-timer

**Comment by avijit-ordering** [comment]
@vydimitrov  With that code it's not working for me. It's still working with 2 seconds. If you have any succession then please share with me.

**Comment by vydimitrov** [comment]
Can you create a ExpoSnack reproducing your issue so I can take a look on what is the problem exactly?

**Comment by avijit-ordering** [comment]
@vydimitrov I have checked with other devices, and there it's working as normal. I am closing this ticket.
Thanks.
