### ISSUE TITLE
onComplete method is called multiple times

### ISSUE THREAD

**Issue by dmitryweiner** [vydimitrov/react-countdown-circle-timer#24]
How to reproduce:
* Create react app
npx create-react-app %app_name%
* Install 
npm i -D react-countdown-circle-timer
* Insert timer into main screen
```
function App() {
  return (
         <CountdownCircleTimer
        key={1}
        isPlaying
        duration={10}
        colors={[['#004777', 0.33], ['#F7B801', 0.33], ['#A30000']]}
        onComplete={() => {
          console.log('timer complete');
          return [true, 1000];
        }}
      >
        {({ remainingTime }) => remainingTime}
      </CountdownCircleTimer>
  );
}
```
* Run dev webserver
npm run start
* Open console
![console.log](https://user-images.githubusercontent.com/6175334/83095852-741d3600-a0ce-11ea-947d-413c704dcd3c.png)

Here you can see the code: https://github.com/dmitryweiner/test-countdown-timer

This bug disappears when you build the project with "npm run build".

**Comment by vydimitrov** [comment]
The bug is caused by `React.StrictMode`, which bugs it in development - https://github.com/dmitryweiner/test-countdown-timer/blob/master/src/index.js#L8

I will investigate it and let you know the result.

**Comment by vydimitrov** [comment]
Some more info here - https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

**Comment by vydimitrov** [comment]
I will fix it and update you

**Comment by jierm2** [comment]
same here, any update on this?
