### ISSUE TITLE
Error: Timer causes apk to crash

### ISSUE THREAD

**Issue by botondburgmann** [vydimitrov/react-countdown-circle-timer#241]
Hi, I have an app that uses this timer component, and it works completely well with Expo Go. But when I build and install an apk on my phone and use it as an android app, when it should show the timer the app just closes. Can anyone help why it does this and how to solve the problem? I have Android version 14

**Comment by vydimitrov** [comment]
Hey, did you install the peer-dependency `react-native-svg`?

**Comment by Bellarose143** [comment]
Installing svg fixed for me

**Comment by botondburgmann** [comment]
Thank you, I installed it and it fixed for me.
