### ISSUE TITLE
Is it possible add MM:SS format to timer?

### ISSUE THREAD

**Issue by nafasebra** [vydimitrov/react-countdown-circle-timer#249]
Is it possible which we add minute : second format like this?

![image](https://github.com/user-attachments/assets/c04620b8-0a0b-4057-8651-ef0d114e0b24)

**Comment by vydimitrov** [comment]
Yup, the component gives you `remainingTime` in seconds which you can format the way you want it.

**Comment by nafasebra** [comment]
Thank you 🙏🏻
