### ISSUE TITLE
Is it possible to countdown with different time spans (e.g. negative, or counting up)?

### ISSUE THREAD

**Issue by ropinheiro** [vydimitrov/react-countdown-circle-timer#26]
I understand that I can set the duration to 20 minutes by e. g. filling it with 20 (minutes) x 60 (seconds).  That will make the component to start counting down from 1200 seconds to 0 (or 20 minutes to 0).

But I have here a use case that is: count down 10 minutes, then count up 10 minutes (with different colors being shown). I see this being implemented as a more flexible time span: instead of going down from 1200 seconds to 0, I want to go from -600 seconds to 600 seconds. Is it possible with the current API? I tried to use the InitialRemainingTime but no luck. Maybe instead of duration, we could have just a startTime and an endTime, then the actual duration = 1200 would be equal to startTime = 1200 and endTime = 0. Now if we want to change the direction of the countdown, we just change the values (startTime = 0 and endTime = 1200). And if we want to have the effect I mentioned before, we would have startTime = -600 and endTime = 600. All this withouth changing the countdown behavior.

Actually I will try to mimic this with some function that gets the renderTime and converts it to my interval. But I think that it would be nice to have this feature builtin.

**Comment by vydimitrov** [comment]
I will keep in mind your request. In case more people request it then I will consider extending the API.
