### ISSUE TITLE
Unable to pass the duration as a parent prop

### ISSUE THREAD

**Issue by ropinheiro** [vydimitrov/react-countdown-circle-timer#27]
I have this working properly:

```
export default function TimerField (props) {
  return (
    <div className='timer-wrapper'>
      <CountdownCircleTimer
        onComplete={() => [true, 1000]}
        duration={20}                                      <===
(...)

```
And even this:

```
const durationInSeconds = 20                   <===

export default function TimerField (props) {
  return (
    <div className='timer-wrapper'>
      <CountdownCircleTimer
        onComplete={() => [true, 1000]}
        duration={durationInSeconds}          <===
(...)

```
But when I try something more better structured like this:

```
export default function TimerField (props) {
  const { durationInSeconds } = props     <===
  return (
    <div className='timer-wrapper'>
      <CountdownCircleTimer
        onComplete={() => [true, 1000]}
        duration={durationInSeconds}        <===
(...)
```
It works for one cycle, then it fails before the second cycle with the following error:

![image](https://user-images.githubusercontent.com/19519494/84675754-98796f00-af24-11ea-9c59-4887aa11b69a.png)

It seems that `duration` must be some "global constant" for this to work properly. Why can't it be a prop?

**Comment by vydimitrov** [comment]
Hey, it really doesn't matter how to you pass the duration to the component, as long as it is a number it it going to work. However, I suspect that the `colors` you are feeding the component is not correct.

Can you share a bit more of your code or even better create a Codesandbox reproducing the issue and I will take a look on it?

**Comment by ropinheiro** [comment]
Sure, here is it:
https://codesandbox.io/s/frosty-https-p0c7y

As you can see, it starts with a countdown timer starting at 4, as defined here:

![image](https://user-images.githubusercontent.com/19519494/84785861-e608e100-afe3-11ea-9b2a-11831211f1a8.png)

When it reaches zero, because `onComplete` is set to `true`, it tries to start a second cycle and raises exception:

![image](https://user-images.githubusercontent.com/19519494/84785949-05a00980-afe4-11ea-8b16-86cad6aa55cc.png)


If you remove the `props.` here, making the duration now being feed by the `durationInSeconds` local constant:

![image](https://user-images.githubusercontent.com/19519494/84786070-2a947c80-afe4-11ea-8474-63992f70ac0e.png)

You will now see the countdown timer starting at 20, doing a full circle then starting again, endlessly.

For any reason, passing the duration as a prop causes this problem. Not sure why. I really need this construction, as I have the Timer under some other covering components and the duration must be provided by prop.

**Comment by vydimitrov** [comment]
Your problem is that `props.durationInSeconds` is a string, it should number 

```jsx
      <TimerField
        // TODO: how to have this working?
        durationInSeconds="4" <----- this should be number, like  durationInSeconds={4}
      />
```

I am not sure why you don't see warnings from `prop-types` but `duration` should be a number. Also `colors` props is not correctly set, you are missing the transition duration next to each color:

```jsx
 <CountdownCircleTimer
      isPlaying
      duration={props.durationInSeconds}
      colors={[["#00FF00"], ["#FF0000"]]} <----- this is wrong value for colors
      onComplete={() => [true, 1000]}
    >
```

Below is the correct way to set the `colors`, you can adjust  the numbers
`colors={[["#00FF00", 0.5], ["#FF0000", 0.5]]}`

Please review the [list of props](https://github.com/vydimitrov/react-countdown-circle-timer#props-for-both-reactreact-native), their types and how you can use them.

**Comment by vydimitrov** [comment]
I am closing this one. Let me know if something is not clear.

**Comment by ropinheiro** [comment]
OMG, that was it. The '20' instead of {20}. I really don't understand how could I miss that after looking hundreds of times to the code :( Thank you very much!

**Comment by ropinheiro** [comment]
About the colors, it was just a demo, I have that part a bit more complicated to force some nuances (and it is working), but thank you for the additional correction detail!
