### ISSUE TITLE
Restart timer with new duration on complete

### ISSUE THREAD

**Issue by ringalls2020** [vydimitrov/react-countdown-circle-timer#29]
I have an array of integers that I would like the timer to map through and use as the new duration each time it completes a countdown. Currently, I call the onComplete function set the duration variable to the next index of the array, then change the key variable, return shouldRepeat as true. It looks like this:

`export default function Timer(){
const array = [10, 20, 30, 25, 15];
const [key, setKey] = useState(1);
const [index, setIndex]= useState(0);
const [time, setTime] = useState(array[0]);

const handleComplete = () => {
setIndex(index +1);
setTime(array[index]);
setKey(key+1);
return [true, 0];
}

return (
<CountdownTimer
key={key}
duration={time}
colors={[["#004777", 0.33], ["#F7B801", 0.33], ["#A30000"]]}
onComplete={handleComplete}
>
{({ remainingTime, animatedColor }) => (
          <Animated.Text
            style={{
              color: animatedColor,
              fontSize: 90,
              fontFamily: "Verdana-Bold",
            }}
          >
            {remainingTime}
          </Animated.Text>
        )}
</CountdownCircleTimer>
);
}`

The issue is that this causes an error: 
_Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s, a useEffect cleanup function, 
    in CountdownCircleTimer (at _timer.js:82)__

Does anyone have any insight into how to fix this?``

**Comment by vydimitrov** [comment]
Hey, thanks for reporting this issue. It seems the `setTimeout` in the onComplete handler is not cleared [here](https://github.com/vydimitrov/react-countdown-circle-timer/blob/master/packages/mobile/src/hooks/useCountdown.js#L82). I will try to fix it as soon as possible.

**Comment by vydimitrov** [comment]
By the way, this should be a warning not an error :)

**Comment by ringalls2020** [comment]
Yes, you are correct, it is a warning rather than an error.

**Comment by vydimitrov** [comment]
Hey @ringalls2020, the warning is now fixed. By the way, if you are changing the `key` of the component you don't need to return `return [true, 0];` in the `onComplete` handlers since the component will be unmounted anyhow so the repeat won't happen. Also you can simplify your code a bit by remove the `setKey` and just use the array index as component's key, like so `key={index}`.

Let me know if you need anything else from me.
