### ISSUE TITLE
startAt doesn't work

### ISSUE THREAD

**Issue by alanzchen** [vydimitrov/react-countdown-circle-timer#3]
https://codesandbox.io/s/cranky-ardinghelli-qfxqu?fontsize=14&hidenavigation=1&theme=dark

```
      <CountdownCircleTimer
        isPlaying
        durationSeconds={60}
        startAt={20}
        colors={[["#A30000"]]}
        renderTime={renderTime}
      />
```

The countdown starts at 60 seconds.

**Comment by vydimitrov** [comment]
Hey, `startAt` prop was introduced in version `1.0.6`, after upgrading react-countdown-circle-timer to 1.0.6, it works now - https://codesandbox.io/s/trusting-kalam-unj0x

**Comment by vydimitrov** [comment]
It seems `startAt` does not reflect very well what it does in the context of countdown (it makes more sense in the context of count up). I will rename that prop to more accurately reflect what it does. I will also keep `startAt` for backward compatibility.
