### ISSUE TITLE
Make `onComplete` async

### ISSUE THREAD

**Issue by ldipasquale** [vydimitrov/react-countdown-circle-timer#30]
hi @vydimitrov! thanks for this amazing library :)

I am wondering if you can make the `onComplete` callback async. I am getting this error if I try to use an async function:

```
Uncaught TypeError: Invalid attempt to destructure non-iterable instance.
```

I thinks it's because `useCountdown.js:59`, so probably will be solved if we modify to:

```
        ? async (...rest) => {
            // REFACTOR in next major release so onComplete matches expected return value as useElapsedTime
            const [shouldRepeat = false, delay = 0] = await onComplete(...rest) || []

            return { shouldRepeat, delay: delay / 1000, newStartAt: 0 }
          }
```

thanks again!

**Comment by vydimitrov** [comment]
Hey @ldipasquale, that sounds interesting :) What is the use case you are having? I am just trying to understand what would be the benefit of it. Can you also fork the repo and test the thing you are suggesting? I guess we will need to make the change in the `useElapsedTime` hook [here](https://github.com/vydimitrov/use-elapsed-time/blob/master/src/hooks/useElapsedTime.js#L52).

**Comment by ldipasquale** [comment]
hi! I am developing a boardgame and I am trying to trigger a request when the player has no more time (and I am using the library to make it happen), so I want to pass an async `onComplete`. I tried to fork the repo but yes, I also need to fork the `use-ellapsed-time` one, right?

**Comment by vydimitrov** [comment]
Yup, that is right. I can take a look on this one tomorrow. As a temporary workaround I would suggest that you do your `async` calls in the `onComplete` handler and if you need to repeat the animation that you change a `key` prop of the component as suggested [here](https://github.com/vydimitrov/react-countdown-circle-timer/tree/master/packages/web#restart-timer-at-any-given-time) and the countdown will start over.

**Comment by ldipasquale** [comment]
ok! thanks. let me know when you take a look on `use-ellapsed-time` and I will submit a pull request regarding this repo. thanks again :)

as a workaround I am defining a callback when pass the `duration` seconds, but I will prefer to use the `onComplete` method :)

**Comment by vydimitrov** [comment]
Hey, I came up with somewhat solution for this but there are a few things to consider:
- I don't want to use `async` `await` in the component because that will require adding some `regenerator-runtime`, which is adding 5KB to the bundle of hook witch is less than 4KB in the case of the `use-elapsed-time`
- I would prefer to not including any polyfills in the component
- We need to make sure that this is not a breaking change and all tests are passing as before
- IE does not support `Promise` so we need to make sure it does not break for the people who are not using promised based onComplete

Below is my solution that I came up for the `use-elapsed-time` hook. Please check it and let me know what you think. It is not perfect but this is the best I was able to come up with for now.

```js
const handleComplete = (options = {}) => {
        const { shouldRepeat = false, delay = 0, newStartAt } = options
        if (shouldRepeat && isMountedRef.current) {
          repeatTimeoutRef.current = setTimeout(() => {
            reset(newStartAt)
          }, delay * 1000)
        }
      }

      totalElapsedTime.current += duration * 1000
      // convert back to seconds
      const totalElapsedTimeSec = totalElapsedTime.current / 1000
      const onCompleteResult = onComplete(totalElapsedTimeSec)

      // onCompleteResult instanceof Promise --- can not be used here since we are not polyfilling Promise,
      // which is not supported by IE (breaks IE). Instead we check for the "then" method on the onCompleteResult
      if (
        'then' in onCompleteResult &&
        typeof onCompleteResult.then === 'function'
      ) {
        onCompleteResult
          .then(handleComplete)
          .catch((error) =>
            console.error(
              'Promise rejection in use-elapsed-time onComplete handler',
              error
            )
          )
      } else {
        handleComplete(onCompleteResult)
      }
```

**Comment by ldipasquale** [comment]
hey! don't worry about it. I will use a timeout that will handle, I thought that adding the `async`/`await` will solve it but makes sense to preserve the bundle.

I have another question (I could create another ticket but I will ask you first here): will be possible to add a `until`/`date` prop to the countdown? I am trying to get the difference between a date and now and show the remaining seconds as https://github.com/ndresx/react-countdown but with the beauty of this library :p.

I am trying to do it and send you the pull request but will make sense adding the feature in `use-elapsed-time` and use in `react-countdown-circle-timer`, right?

**Comment by vydimitrov** [comment]
Sure thing, lets keep this as a feature request. If it happens that more people request it that I will add it to the library. 

I will close this issue for now. Thank you for contributing to this project.

**Comment by TuCOSMOPOLIS** [comment]
hi for use async functions in onComplete i create an async function and call it from onComplete, something like this

onComplete = () => {
this.asyncFunction();
}

asyncFunction = async () => {
await ....
}

**Comment by vydimitrov** [comment]
Yup, that is going to work 👍
