### ISSUE TITLE
How can i give end date?

### ISSUE THREAD

**Issue by muserrefakillibaykus** [vydimitrov/react-countdown-circle-timer#32]
How can i give finished date to countdown?

https://codesandbox.io/s/musing-davinci-mqssz?fontsize=14&hidenavigation=1&theme=dark

**Comment by vydimitrov** [comment]
Just change the value of the `endDate` variable to your end date. Remember to pass the value in seconds for both `startDate` and `endDate`. You can do this
`const endDate = new Date('2012.08.10').getTime() / 1000` to convert date to unix timestamp in seconds.

Read more here - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime

**Comment by muserrefakillibaykus** [comment]
It works! Thank you so much.

**Comment by vydimitrov** [comment]
Great! Let me know if you need any additional help with the component.
