### ISSUE TITLE
Error import

### ISSUE THREAD

**Issue by faisalaja** [vydimitrov/react-countdown-circle-timer#33]
I've problem for use your lib, this is message error:
./node_modules/react-native-countdown-circle-timer/lib/index.js
Module not found: Can't resolve 'react-native' in /.../...

**Comment by vydimitrov** [comment]
Have you added `react-native` to your project? Do you use it for Mobile or Web? The Web package is `react-countdown-circle-timer`.

**Comment by vydimitrov** [comment]
Let me know if you need any additinal help.
