### ISSUE TITLE
Request for a new feature: the ability to pause

### ISSUE THREAD

**Issue by MyNameIsHung** [vydimitrov/react-countdown-circle-timer#35]

**Comment by vydimitrov** [comment]
Hey @MyNameIsHung, this feature already exists. You just need to set `isPlaying` to false. Check the list of [avaiable props](https://github.com/vydimitrov/react-countdown-circle-timer#props-for-both-reactreact-native)

**Comment by MyNameIsHung** [comment]
Oh rlly thanks
