### ISSUE TITLE
How To Give Min and Max Sizes?

### ISSUE THREAD

**Issue by zhg-kj** [vydimitrov/react-countdown-circle-timer#36]
I'm trying to make a responsive React app using your component. From the documentation it looks like I can only enter numbers for the size but I need the component to scale accordingly to the users view width. Anyway I can do this?

**Comment by vydimitrov** [comment]
Hey, I would recommend using something like [react-sizeme](https://github.com/ctrlplusb/react-sizeme) to get the view port width and feed that into the timer component.
