### ISSUE TITLE
No differnce appears in stroke

### ISSUE THREAD

**Issue by gulsher7** [vydimitrov/react-countdown-circle-timer#40]
![Screenshot 2020-07-19 at 5 15 51 PM](https://user-images.githubusercontent.com/56266123/87874062-51c7da80-c9e4-11ea-938f-d666d81b43a1.png)

Hey Developer.... It takes a lot of time to see the differnce in strokeLine when i increase the duration time...Please resolve it as soon as possible..

**Comment by vydimitrov** [comment]
Hey, of course it takes a lot of time when you increase the duration since the timer will need to almost 6 hours to make the full circle. So I can tell you for sure that if you wait 3 hours then the progress will be at half.

**Comment by vydimitrov** [comment]
This is simple math, I hope you understand that. Imagine that you have 6 hours to do 100 meters, if I look at you 5 minutes after you started you would be at the same place where you stared since you have big time span to go over 100 meters.
