### ISSUE TITLE
Reset Timer in Middle of Countdown

### ISSUE THREAD

**Issue by heisjohn** [vydimitrov/react-countdown-circle-timer#43]
Thanks for this library!
I was wondering if it is possible to reset the timer, but not through onComplete? I am trying to implement something where the timer freezes when a modal opens on the screen, and the user may click a button to reset the timer. However, I have not been able to figure out how to make the timer restart without waiting for it to count all the way down to 0. For example, the timer is counting down from 20, the user clicks on the screen and opens a modal, timer freezes at 15, and the user clicks restart, which starts the timer back at 20.
Again, thanks so much.

**Comment by vydimitrov** [comment]
Hey @heisjohn, yup, this is possible. Please refer to [Restart/Reset timer recipe](https://github.com/vydimitrov/react-countdown-circle-timer/blob/master/README.md#restartreset-timer-at-any-given-time) on the Readme page.

Let me know if you need any additional help.

**Comment by heisjohn** [comment]
Oh, I see. Sorry I glanced over that. Thanks for your help. Feel free to close this now.

**Comment by vydimitrov** [comment]
Cool 👍
