### ISSUE TITLE
You should add dynamic duration and initial time change possibility.

### ISSUE THREAD

**Issue by SergiOnGit** [vydimitrov/react-countdown-circle-timer#45]
I like this plugin very much but it lacks the feature i need the most "dynamic duration and initial time change possibility". Add it and this will be the best react native circle countdown plugin.

**Comment by vydimitrov** [comment]
Hey @SergiOnGit, both of these are possible with the current API. To change initial time just pass `initialRemainingTime` to the component as describe in the props section. Dynamic duration is possible by passing a new `key` prop to the component as described [in the recipes](https://github.com/vydimitrov/react-countdown-circle-timer#change-duration-andor-initialremainingtime-once-component-is-mounted). Let me know if you need any additional help setting these up.

**Comment by SergiOnGit** [comment]
Thanks for your response @vydimitrov 

I was confused by first sentence of recipes "Change duration and/or initialRemainingTime once component is mounted". It is great then. I'm going to use this repo in my production apps.
