### ISSUE TITLE
Lack of docs

### ISSUE THREAD

**Issue by SergiOnGit** [vydimitrov/react-countdown-circle-timer#46]
I didn't find demo of third animation https://user-images.githubusercontent.com/10707142/65963815-cfbdf380-e45b-11e9-809d-970174e88914.gif

Can you help with this? @vydimitrov  Even a tutorial how to achieve this animation is accepted.

**Comment by vydimitrov** [comment]
Hey @SergiOnGit, take a look on the Web version of the animation to get inspired and build it yourself for React Native using Animated. 

https://github.com/vydimitrov/react-countdown-circle-timer/tree/master/packages/web#slide-down-time-animation

**Comment by SergiOnGit** [comment]
Thank you, the link is helpful and i think i can handle it now @vydimitrov

**Comment by vydimitrov** [comment]
I'd appreciate if you can recreate that animation for React Native and add it to the Readme, like I did for the Web project. I will be happy to accept that PR :)

**Comment by SergiOnGit** [comment]
@vydimitrov I will do it, in case i decide to create this component.

**Comment by AkbarBakhshi** [comment]
Hello @vydimitrov. I created a snack for this. If you want, please feel free to use it however you'd like( as an example in your ReadME or wherever). 

Thanks for this cool library.

https://snack.expo.dev/@akbar89/animated-react-countdown-circle-timer

**Comment by vydimitrov** [comment]
Hah, great, it looks awesome. I will add it to the README for sure. Thanks for creating and sharing the snack :)
