### ISSUE TITLE
onComplete does not reflect props

### ISSUE THREAD

**Issue by cristian-milea** [vydimitrov/react-countdown-circle-timer#47]
Hello,

First of all, thank you for this awesome library.
I have an issue and I don't know if it's a bug or I just implemented it wrong.
So my score prop gets updated, but when `onComplete` gets triggered, it does not reflect the correct value of the prop.

simplified code:
```
const MyComp = ({
score
}) => {
   console.log(score); // ITS OK, UPDATING
   return (
      <CountdownCircleTimer
                isPlaying
                size={60}
                duration={10}
                strokeWidth={5}
                onComplete={() =>{
                    console.log(score); // SHOWS 0
               }}
                colors={[[Colors[colorScheme].tint, 0.33], ['#F7B801', 0.33], ['#A30000']]}>
                {({ remainingTime, animatedColor }) => (
                  <Animated.Text
                    style={{ ...styles.remainingTime, color: animatedColor }}>
                         {remainingTime}
                  </Animated.Text>
                )}
       </CountdownCircleTimer>
   )
}
```

Any advice?

**Comment by vydimitrov** [comment]
Hey @cristian-milea, thanks for reporting this issue. I quickly inspected the code and found that there is an effect that listens for a change in the play state, which also sets the `onComplete` handler and starts/stops animation. That effect has [dependency only on `isPlaying`](https://github.com/vydimitrov/react-countdown-circle-timer/blob/master/packages/mobile/src/hooks/useCountdown.js#L109). Any other change of the props won't trigger the effect, which means that `onComplete` will point to the function that was initially passed. Thus, it will use the value in the closure from the moment it was passed to the component, a.k.a it won't use the latest value of `score`but its initial value. Does this make sense? 

I will spend some time and try to find some solution for it.

**Comment by vydimitrov** [comment]
Hey @cristian-milea, until I fix it, as a workaround you can update local state when `onComplete` is triggered and read your `score` and act accordingly :) Let me know if that is helpful.

**Comment by cristian-milea** [comment]
> , as a workaround you can update local state when

hi @vydimitrov , thanks for your reply.

That's what I did for now, used a local state + effect to trigger an action.

```
useEffect(() => {
    if(gameOver) timeUpCallback();
  }, [gameOver])
const timeUp = useCallback(
    () => {
      setGameOver(true);
      return [false]
    },
    [],
)

**Comment by vydimitrov** [comment]
Hey @cristian-milea, this bug is now fixed. I added `onComplete` to the hook dependencies and it updates correctly. Please pull the latest version `2.3.8` and let me know if it works for you.

**Comment by cristian-milea** [comment]
> Hey @cristian-milea, this bug is now fixed. I added `onComplete` to the hook dependencies and it updates correctly. Please pull the latest version `2.3.8` and let me know if it works for you.

it works, thank you!
