### ISSUE TITLE
onComplete method not working if App in background mode

### ISSUE THREAD

**Issue by 31Karishma** [vydimitrov/react-countdown-circle-timer#49]

**Comment by vydimitrov** [comment]
Hey @31Karishma, I already investigated this issue. You can read me findings [here]( https://github.com/vydimitrov/react-countdown-circle-timer/issues/7#issuecomment-590054355). In a nutshell, Chrome will pause `requestAnimationFrame ` until the moment the tab gets focused again then `onComplete` will fire if the time is over.
