### ISSUE TITLE
Typescript error: has no exported member 'Config'

### ISSUE THREAD

**Issue by pkm52000** [vydimitrov/react-countdown-circle-timer#5]
Error:(42, 33) TS2694: Namespace '"../node_modules/use-elapsed-time/types/use-elapsed-time"' has no exported member 'Config'.

Version: 1.1.0

onComplete appear that it needs to be defined as a type.

**Comment by vydimitrov** [comment]
Hey, I tried to reproduce it but it seems fine. Check my demo here - https://codesandbox.io/s/gracious-dust-dwptd

Please create a codesandbox if you know how to reproduce it.

**Comment by pkm52000** [comment]
Hey @vydimitrov,

I got this error mainly when building. I am using frontend-maven-plugin to build which throws the above error. I also managed to see the error when navigating to the typing definition file in IntelliJ in the Typescript window.

I'll try setup a new project to test again.

**Comment by bheftyes** [comment]
Hi I have the same issue using TypeScript.

```bash
yarn run v1.22.5
$ tsc
node_modules/react-native-countdown-circle-timer/types/CountdownCircleTimer.d.ts:2:24 - error TS2307: Cannot find module 'use-elapsed-time' or its corresponding type declarations.

2 import { Config } from 'use-elapsed-time'
                         ~~~~~~~~~~~~~~~~~~


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

From the actual code:
CountdownCircleTimer.d.ts
```ts
import * as React from 'react'
import { Config } from 'use-elapsed-time'

export type OnComplete = Config['onComplete']
...
```
