### ISSUE TITLE
Mobile: countdown does not repeat when using useState function update in onComplete

### ISSUE THREAD

**Issue by vydimitrov** [vydimitrov/react-countdown-circle-timer#51]
This bug affects only React Native countdown timer. The Web/React version on the countdown timer works as expected.

It was found that when using `useState` functional update in `onComplete` handler, the animation does not repeat when the handler returns props to repeat animation. Issue signature:

```js
const [count, setCount] = useState(0)

<CountdodnCircleTimer
  {...props}
  onComplete={() => {
    setCount(count => count + 1) // setCount function update
    return [true, 0]
  }}
/>
```
It can be reproduced in [this expo shank](https://snack.expo.io/@vydimitrov/countdown-oncomplete-issue?session_id=snack-session-8tgDhia5f&preview=true&platform=ios&iframeId=4a80oah677&theme=light)

However, if we pass a new state value to `setCount` the timer works as expected, as seen below:
```js
const [count, setCount] = useState(0)

<CountdodnCircleTimer
  {...props}
  onComplete={() => {
    setCount(1) // new state value
    return [true, 0]
  }}
/>
```
It can be tested in [this expo snack](https://snack.expo.io/@vydimitrov/countdown-oncomplete-wokring?session_id=snack-session-8tgDhia5f&preview=true&platform=ios&iframeId=4a80oah677&theme=light).

## Temporary workaround
If you need to do an update on a value in `onComplete` that depends on the previous value, a.k.a using `useState` function update, you can do the following:
- use `useRef` to keep track of your value and update it inside the `onComplete` handler
- pass a new random state value in `onComplete`, which will cause the component to rerender and use the new value from the `useRef`
```js
const countRef = useRef(0)
const [completedTime, setCompletedTime] = useState(0)

<CountdodnCircleTimer
  {...props}
  onComplete={() => {
    countRef.current += 1
    setCompletedTime(Date.now()) // new value every time it hits the onComplete
    return [true, 0]
  }}
/>

return <p>{countRef.current}</p>
```
## Findings
The `useEffect` that handles start/stop animation and `onComplete` callbacks is defined in [here](https://github.com/vydimitrov/react-countdown-circle-timer/blob/master/packages/mobile/src/hooks/useCountdown.js#L73). If we remove the `onComplete` handler from [the array of dependency](https://github.com/vydimitrov/react-countdown-circle-timer/blob/master/packages/mobile/src/hooks/useCountdown.js#L109) then `useState`  function updates work as expected.

**Comment by JRyanSaunders** [comment]
Hi @vydimitrov  I have been messaging you on twitter under the name Kappiey. I have been trying to implement this in my project for a couple of days now but I can't get it to work. I was wondering if you could take a look at my project to get it working?

https://github.com/JRyanSaunders/Fitness-App

**Comment by vydimitrov** [comment]
Hey @JRyanSaunders, your app helped me a lot to find the root cause of the bug, thanks for sharing it. The issue was caused by a loop in the `onComplete` callback. Since we were setting state in the callback, the parent component was re-rendered thus a new instance of the `onComplete` callback was passed, which caused to run the callback in a loop.

To solve it, I am now checking if we are in finished state and it that is the case I don't call the callback again. Below is the commit that fixes the issue:
https://github.com/vydimitrov/react-countdown-circle-timer/commit/0ea726da6d91cb197a41ebb0034702ea799dc8e8

Please upgrade the package to `2.3.9` and you should have it fixed now.

Thanks for your time 👍

**Comment by JRyanSaunders** [comment]
I'm glad I could help @vydimitrov - thanks for making such a useful component! I have reverted back to my original code and everything is working perfectly now!
