### ISSUE TITLE
Number size not changing with circle - react-native

### ISSUE THREAD

**Issue by matt-bendel** [vydimitrov/react-countdown-circle-timer#54]
Whenever changing the size prop, the number stays very small.

Here is how I have it setup:
`<CountdownCircleTimer
              isPlaying
              size={250}
              duration={5}
              colors={[
                ['#D9B6FF', 0.4],
                ['#ce03fc', 0.4],
                ['#F758A5', 0.2],
              ]}
              onComplete={this.props.onZero}>
              {({remainingTime, animatedColor}) => (
                <Animated.Text style={{color: animatedColor}}>
                  {remainingTime}
                </Animated.Text>
              )}
            </CountdownCircleTimer>
`

Here is a screenshot:
![Simulator Screen Shot - iPhone 11 - 2020-09-16 at 13 43 57](https://user-images.githubusercontent.com/50177129/93373028-c2dc1080-f822-11ea-8ded-07bb867eb946.png)

**Comment by vydimitrov** [comment]
Hey @matt-bendel, have you looked at the [documentation about the `size` prop](https://github.com/vydimitrov/react-countdown-circle-timer#props-for-both-reactreact-native). This would be a good start for you. 

You can change the font size of the text as it is done here in [this demo. ](https://github.com/vydimitrov/react-countdown-circle-timer/tree/master/packages/mobile#demo)

**Comment by matt-bendel** [comment]
Wow I'm an idiot. Thank you for the quick reply and a wonderful component!
