### ISSUE TITLE
onComplete not working on inactive tab

### ISSUE THREAD

**Issue by RadoRakotozafy** [vydimitrov/react-countdown-circle-timer#57]
The onComplete function is not triggered when we are on a different tab. It gets executed only when we come back.

**Comment by RadoRakotozafy** [comment]
The same behaviour happen on load.

**Comment by vydimitrov** [comment]
This issue was already discussed. Please refer to [this comment I left](https://github.com/vydimitrov/react-countdown-circle-timer/issues/7#issuecomment-590054355)
