### ISSUE TITLE
Custom countdown circle

### ISSUE THREAD

**Issue by lacsinagramar** [vydimitrov/react-countdown-circle-timer#59]
Hi, is there any way I can edit the circle of the timer?

**Comment by vydimitrov** [comment]
[There are bunch of props](https://github.com/vydimitrov/react-countdown-circle-timer#props-for-both-reactreact-native) that you can change to customize the timer cirle.

**Comment by lacsinagramar** [comment]
Uh yes, sorry I did not make myself clear. What I meant is, is there any way I can have a custom SVG of the Circle timer.

Something like this:
![image](https://user-images.githubusercontent.com/29629828/96273936-80b11500-1002-11eb-9579-0a67ed1bd65f.png)

The dots there are based on a specific time. (e.g On 10:00 there will be a dot on the timer)

**Comment by vydimitrov** [comment]
This looks good. But the component does not have anything out of the box, which would allow you to build it. If you have any idea how you can do it I am ready to help you.

**Comment by vydimitrov** [comment]
Hey @lacsinagramar, I am closing this bug for now. Let me know if you need anything else from my side.
