### ISSUE TITLE
Add timer to the notification bar while the app is running in background

### ISSUE THREAD

**Issue by joaonunogomes** [vydimitrov/react-countdown-circle-timer#61]
Hi! First of all great library!
Is it possible to add the timer to the notification bar while the app is running in background?

**Comment by vydimitrov** [comment]
Hey @joaonunogomes, is it about Mobile and React Native? I am not sure how animations are handled in Mobile while the app in running in the background. On desktop, while the tab is not active the `requestAnimationFrame` calls will be reduced or suspended so it does not consume CPU. Thus you can not relay that the timer will go smoothly while the tab is not focused.

**Comment by joaonunogomes** [comment]
Hi @vydimitrov, thanks for your quick reply.
My use case is with Mobile and react native, sorry for the lack of context.
I have tested a few times and the timer seems to work smoothly while the app is not on background.
My goal here would be to have the timer also running on notification bar if the app is in background.
Something like the behavior of Android clock timer when the timer is on background.

**Comment by vydimitrov** [comment]
I see now ... unfortunately, I don't have any experience with that. Let me know if you manage to add the timer to the notification bar tho.

**Comment by joaonunogomes** [comment]
I will. Thanks for the help :)

**Comment by GaylordP** [comment]
Hi @joaonunogomes ,

I have the same problem, did you find a solution? Thank you so much :)
