### ISSUE TITLE
useState update don't update countdown

### ISSUE THREAD

**Issue by vincepich** [vydimitrov/react-countdown-circle-timer#62]
I created this example https://codesandbox.io/s/countdown-circle-example-ij0nf 
and i don't understand why the countdown control not refresh remainingTime when I click on update button.
Is it my mistake or did I not set something well?

**Comment by vydimitrov** [comment]
Hey @vincepich, [here](https://github.com/vydimitrov/react-countdown-circle-timer#change-duration-andor-initialremainingtime-once-component-is-mounted) is your answer. Let me know if I can help you in any other way.

**Comment by vincepich** [comment]
Thank you very much! I had read quickly and did not realize that I had to regenerate the key.
