### ISSUE TITLE
Focus on passed time

### ISSUE THREAD

**Issue by rendomnet** [vydimitrov/react-countdown-circle-timer#63]
I want to focus not on remaining time but on passed time.
"Select" with color the line of passed time. strokeLinecap should mark passed time not remaining time.

**Comment by vydimitrov** [comment]
This is the closest I can get to https://codesandbox.io/s/naughty-morning-f006t?file=/src/index.js

**Comment by vydimitrov** [comment]
I am closing this one ... let me know if I can help you in any other way.
