### ISSUE TITLE
Cancel timers in componentWillUnmount

### ISSUE THREAD

**Issue by celandro** [vydimitrov/react-countdown-circle-timer#64]
The current implementation leaks memory as it does not cancel the onComplete timer when the component is unmounted.

All timers should be stopped on unmount

Edit: This appears to have been due to the tab component I was using not truly unmounting the components.

**Comment by vydimitrov** [comment]
Yuo, just for refrence [this code](https://github.com/vydimitrov/use-elapsed-time/blob/master/src/hooks/useElapsedTime.js#L75) will make sure to clean it all.
