### ISSUE TITLE
Required to switch the transition only between two color green and red.

### ISSUE THREAD

**Issue by RanaVaibhav92** [vydimitrov/react-countdown-circle-timer#65]
There is a requirement to changes the timer color only in 2 given colors. Is there any way to achieve this .

**Comment by vydimitrov** [comment]
Hey, do you want the change between the two colors to be sudden without any transtion between them? If that is what you want, you can do it like this:
https://codesandbox.io/s/patient-browser-gmsmh?file=/src/index.js

**Comment by RanaVaibhav92** [comment]
Thank you very much for the help.
