### ISSUE TITLE
Can we use this timer as a circular progress bar.

### ISSUE THREAD

**Issue by RanaVaibhav92** [vydimitrov/react-countdown-circle-timer#66]
There is requirement to create a circular progress bar i tried to use it but there is a problem while using this a circular bar the timer is not getting updated when i am just updating the initialRemainingTime the circular bar is not getting updated. Please let me know is there any scope for using this module the way i am trying to use it.

**Comment by vydimitrov** [comment]
Hey, please read the README and you will find the answer to your question.

**Comment by vydimitrov** [comment]
Check it here https://github.com/vydimitrov/react-countdown-circle-timer#change-duration-andor-initialremainingtime-once-component-is-mounted

**Comment by RanaVaibhav92** [comment]
Thanks for the help got the solution.
