### ISSUE TITLE
[compatibility] version 2.3.11 breaks IE 11

### ISSUE THREAD

**Issue by fmagaldea** [vydimitrov/react-countdown-circle-timer#74]
Hi,

Version 2.3.7 works fine, but the next one (2.3.11) breaks IE 11, even with bundle through webpack, babel & co.

I think it's because in the node module the bundled file `lib/index.js` contains several arrow functions, for example it starts with `module.exports=(()=>...` which is not compatible with old browsers.

**Comment by vydimitrov** [comment]
Hey, thanks for reporting the issue. In version 2.3.11 I updated all dependencies including Webpack to v5. I just found out that Webpack in v5 uses ES2015 for the runtime code when browser list is missing, which is the case here. You can read more about it on [here](https://webpack.js.org/migrate/5/#need-to-support-an-older-browser-like-ie-11). I will fix and let you know.

**Comment by vydimitrov** [comment]
I should be now fixed in `2.3.12`. Please retest it and let me know if that fixes the issue.

**Comment by fmagaldea** [comment]
Works perfectly now 👍 

Thanks for your reactivity!

**Comment by vydimitrov** [comment]
Hey @fmagaldea, I just pushed a new version `2.4.0` where I added a list of the supported browsers, and reverted the temp fixed from yesterday. Could you please retest that and let me know if still works as expected on IE11? Thank you.

**Comment by fmagaldea** [comment]
Works as well with 2.4.0 👍

**Comment by vydimitrov** [comment]
Perfect, thank you for checking that!
