### ISSUE TITLE
Timer is lagging / Is slowed down

### ISSUE THREAD

**Issue by SaadAhmadSaddiqui** [vydimitrov/react-countdown-circle-timer#81]
I'm using the timer in React-Native
It was working fine but I just noticed huge lag of some sorts. duration of 10 seconds takes 30+ seconds to finish.
I tried the timer on an empty screen and it was working fine.
I have nothing in the code that slows down to timer, so I was wondering if it's because maybe the page in general too "heavy"?
I'm still new to react-native/react so I'm sorry if it sounds silly.

Love your work with the timer, though.

**Comment by SaadAhmadSaddiqui** [comment]
I found the issue. I had a useEffect in the timer render component with elapsedTime in the dependency. Removing it from the dependency fixed it.

`  const Timer = ({ remainingTime, elapsedTime, animatedColor }) => {
    useEffect(() => {
      setTimer(elapsedTime / 1000)
    }, [elapsedTime]) // removed the dependency here

    return (
      <TimerContainer>
        <AnimatedText
          allowFontScaling={false}
          style={{ fontSize: hp(3), color: animatedColor }}
        >
          {remainingTime}
        </AnimatedText>
      </TimerContainer>
    )
  }`

Although I don't understand why it does what it does. Like I said, still new.

**Comment by vydimitrov** [comment]
Yup, the `elapsedTime` changes approximately every 16ms and you are using it to set state, which causes your component to rerender on top of the rerender that the timer does already. 

What do you do with the elapsedTime when you call setTimer?

**Comment by SaadAhmadSaddiqui** [comment]
I'm making a quiz app and wanted to get the exact time the user submits their answer to score them accordingly. I have managed to figure out a solution tho. 

`const timePassed = useRef(elapsedTime)
    useEffect(() => {
      timePassed.current = elapsedTime / 1000
      console.log(timePassed.current)
    }, [elapsedTime])`

Might not be the cleanest way, but does the job! Let me know if you think there would be a better way to make it happen. Thanks for the reply and help!

**Comment by SaadAhmadSaddiqui** [comment]
I'm making a quiz app and wanted to get the exact time the user submits their answer to score them accordingly. I have managed to figure out a solution tho. 

I wanted to send the last time to an api. And, I solved it by saving the time in a ref, rather than in a state.

```javascript
 ...
 
useEffect(() => {
      timePassed.current = elapsedTime / 1000
    }, [elapsedTime])
```

**Comment by vydimitrov** [comment]
Yup, ref is going to work. Are you going to send it when the component is unmounted, or what is the idea to fire the API request? You may no need to keep it even in ref.

**Comment by SaadAhmadSaddiqui** [comment]
I'm making a quiz app and want to calculate the score according to the `elapsedTime` when the user presses a button. Sort of like Kahoot you could say. With that I do my calculation and send to score to the API.

**Comment by vydimitrov** [comment]
I was asking about the implementation to fire the API request, so I can give you some advice may be :)

**Comment by vydimitrov** [comment]
Closing it for now. Let me know if I can help you in any other way.
