### ISSUE TITLE
Want to make color transition in reverse

### ISSUE THREAD

**Issue by NitishaJPLoft** [vydimitrov/react-countdown-circle-timer#83]
Hello,
I want to do the reverse thing in this process, is it possible that this color transition on the circle should not remove, it should fill the circle.
Can we change trailcolor at the time of progress running?
Please help, I really need it badly.

**Comment by vydimitrov** [comment]
Hey, this is the closest I can get to it - https://codesandbox.io/s/compassionate-rain-p6v20?file=/src/styles.css

**Comment by vydimitrov** [comment]
By the way, this may become a bit easier when we complete this PR - https://github.com/vydimitrov/react-countdown-circle-timer/pull/82

**Comment by vydimitrov** [comment]
Closing this one. Let me know if I can help you with something else.

**Comment by NitishaJPLoft** [comment]
Thanks for the solution
