### ISSUE TITLE
View config not found for name path, make sure to start component names with a capital letter

### ISSUE THREAD

**Issue by AyoubXwire** [vydimitrov/react-countdown-circle-timer#9]
I've just installed the library into my project, and Im getting an error.
Im using the **Basic Usage** snippet:

````js
import { CountdownCircleTimer } from 'react-countdown-circle-timer';

const UrgeWithPleasureComponent = () => (
    <CountdownCircleTimer
        isPlaying
        durationSeconds={10}
        colors={[
            ['#004777', .33],
            ['#F7B801', .33],
            ['#A30000']
        ]}
    />
);
````
and I get this error when I lunch it.: 

`View config not found for name path, make sure to start component names with a capital letter`

whats the problem here??

**Comment by tomercy** [comment]
I have the same issue... please update if you were able to solve it

**Comment by vydimitrov** [comment]
Hey, do you use it in `react-native` project? The component is built for the Web. I will look at making it reusable between the Web and Mobile. 

It works just fine on Web - https://codesandbox.io/s/competent-bogdan-ngz23

**Comment by tomercy** [comment]
Hi @vydimitrov 
Yes, I'm trying to use it in react-native :)
This timer is exactly what I need for my project :D

**Comment by vydimitrov** [comment]
Yup, I will consider making the countdown timer `react-native` friendly. However until then, I would recommend forking this repo, replacing all `div`s with `View`s, install [react-native-svg](https://github.com/react-native-community/react-native-svg) and replace all Web `svg` elements with the one provided by the library. More or less that should be all to make it work :)

**Comment by AyoubXwire** [comment]
> Hey, do you use it in `react-native` project? The component is built for the Web. I will look at making it reusable between the Web and Mobile.
 Thanks for the quick reply, yeah I tried it on react native.. my bad, I taught it was for react native.

also.. I like the feature request.. I really need this library, Thanks a lot!

**Comment by vydimitrov** [comment]
Yup, I will let you know once I decide how I am going to do it .

**Comment by vydimitrov** [comment]
Hey @whenmoon, @tomercy, @AyoubXwire, I just pushed the first version of React Native Countdown Timer to NPM - https://www.npmjs.com/package/react-native-countdown-circle-timer

Please take a look on it and let me know what you think about it.

**Comment by AyoubXwire** [comment]
> Hey @whenmoon, @tomercy, @AyoubXwire, I just pushed the first version of React Native Countdown Timer to NPM - https://www.npmjs.com/package/react-native-countdown-circle-timer
> 
> Please take a look on it and let me know what you think about it.


Now I can use the library on my react native project.. thanks a lot man 🙏
