### ISSUE TITLE
always zero on safari

### ISSUE THREAD

**Issue by fadlulazmi** [vydimitrov/react-countdown-circle-timer#98]

**Comment by vydimitrov** [comment]
It works just fine one Mobile Safari

![1928](https://user-images.githubusercontent.com/10707142/111026205-63357b00-83e9-11eb-80a4-79c4f343548b.jpg)

**Comment by vydimitrov** [comment]
Closing this one due to inactivity.

**Comment by quansenB** [comment]
FYI. I stumbled across a similar issue. It was due to new Date("2021-07-02 19:55") being interpreted differently in Safari (as invalid Date). So if anybody has a similar issue I'd recommend looking in this direction

**Comment by vydimitrov** [comment]
Thanks for sharing it.
